// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Netipam.Data;

#nullable disable

namespace Netipam.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251231021537_AddIgnoreOfflineToDevice")]
    partial class AddIgnoreOfflineToDevice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Netipam.Data.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DarkMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("MM-dd-yyyy HH:mm");

                    b.Property<bool>("ShowLastSeenTooltips")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Netipam");

                    b.Property<int>("UiAutoRefreshSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("UnifiBaseUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnifiPasswordProtected")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnifiSiteName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UnifiUpdateConnectionFieldsWhenOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("UnifiUpdaterEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("UnifiUpdaterIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(60);

                    b.Property<string>("UnifiUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Netipam.Data.ClientOfflineAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CameOnlineAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAtTime")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("NameAtTime")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WentOfflineAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("WentOfflineAtUtc");

                    b.ToTable("ClientOfflineAlerts");
                });

            modelBuilder.Entity("Netipam.Data.ClientType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDevice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ClientTypes");
                });

            modelBuilder.Entity("Netipam.Data.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClientTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HostDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreOffline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastOnlineAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("SourceDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubnetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usage")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsedNew")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientTypeId");

                    b.HasIndex("HostDeviceId");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("SubnetId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Netipam.Data.Subnet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidr")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cidr")
                        .IsUnique();

                    b.ToTable("Subnets");
                });

            modelBuilder.Entity("Netipam.Data.ClientOfflineAlert", b =>
                {
                    b.HasOne("Netipam.Data.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Netipam.Data.Device", b =>
                {
                    b.HasOne("Netipam.Data.ClientType", "ClientType")
                        .WithMany("Devices")
                        .HasForeignKey("ClientTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Netipam.Data.Device", "HostDevice")
                        .WithMany()
                        .HasForeignKey("HostDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Netipam.Data.Subnet", "Subnet")
                        .WithMany("Devices")
                        .HasForeignKey("SubnetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientType");

                    b.Navigation("HostDevice");

                    b.Navigation("Subnet");
                });

            modelBuilder.Entity("Netipam.Data.ClientType", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Netipam.Data.Subnet", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
